Added swiftLint and swiftGen. Refactored code to conform libraries
Yefimchukv/yalantis-test pull request #18
Opened 2021-11-09 13:53 UTC by Yefimchukv

2021-11-13 11:16 UTC, seropusha requested changes
- Довыносить все строки в Localizable.strings

2021-11-13 11:16 UTC, seropusha commented on YalantisTest/Sources/Controllers/YTTabBarController.swift
>          settingsVC.title = "Settings"
добавить в Localizable.srings

2021-11-13 11:16 UTC, seropusha commented on YalantisTest/Resources/Base.lproj/Constants.strings
> +"cells.settingsCell" = "settingsCell";
Можно все в одном файле хранить Localizable.strings

2021-11-13 17:42 UTC, Yefimchukv commented
@seropusha проверь пожалуйста

2021-11-15 16:24 UTC, seropusha approved these changes
Можно мерджить!

2021-11-15 16:34 UTC, merged